site_name: interviewSet
site_url: https://example.com/
nav:
  - 主页: index.md
  - 后端技术栈:
      - python面试: python-interview.md
      - redis: redis.md
  - 面试题库:
      - python: a.md
  - 关于我: about.md
theme: readthedocs
